/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Nha;

import java.io.Serializable;

import MODEL.ModelUser;

/**
 *
 * @author ANH TUAN
 */
public class form1 extends javax.swing.JPanel implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();
    }

    public void check(ModelUser userMD) {
        Id.setText(userMD.getId() + "");
        UserNamee.setText(userMD.getName());
        Balances.setText(userMD.getBalance() + "");
        books.setText(userMD.getNumbersOfBook() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nen1 = new TaoNen.Nen();
        books = new javax.swing.JLabel();
        lbBalance = new javax.swing.JLabel();
        lbNOB1 = new javax.swing.JLabel();
        LbUser1 = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        UserNamee = new javax.swing.JLabel();
        Balances = new javax.swing.JLabel();
        lbNOB2 = new javax.swing.JLabel();
        LbUser2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        setBackground(new java.awt.Color(255, 255, 255));

        books.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        books.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        books.setText("asd");

        lbBalance.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBalance.setText("Your Balance");

        lbNOB1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbNOB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNOB1.setText("Number of Books");

        LbUser1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LbUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbUser1.setText("User Name");

        Id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Id.setText("sa");

        UserNamee.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        UserNamee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserNamee.setText("hahs");

        Balances.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Balances.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Balances.setText("asd");

        lbNOB2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbNOB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNOB2.setText("Have a nice day!");

        LbUser2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LbUser2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbUser2.setText("ID");

        javax.swing.GroupLayout nen1Layout = new javax.swing.GroupLayout(nen1);
        nen1.setLayout(nen1Layout);
        nen1Layout.setHorizontalGroup(
                nen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbNOB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nen1Layout.createSequentialGroup()
                                .addGroup(nen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(nen1Layout.createSequentialGroup()
                                                .addGap(0, 0, 0)
                                                .addGroup(nen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(LbUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(LbUser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lbNOB1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
                                        .addComponent(lbBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(nen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UserNamee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(books, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Balances, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        nen1Layout.setVerticalGroup(
                nen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(nen1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(nen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LbUser2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                        .addComponent(Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(nen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(UserNamee, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LbUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(nen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Balances, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                        .addComponent(lbBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(nen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbNOB1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(books, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNOB2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JLabel Balances;

    public javax.swing.JLabel getBalances() {
        return Balances;
    }

    public void setBalances(javax.swing.JLabel balances) {
        Balances = balances;
    }

    private javax.swing.JLabel Id;

    public javax.swing.JLabel getId() {
        return Id;
    }

    public void setId(javax.swing.JLabel id) {
        Id = id;
    }

    private javax.swing.JLabel LbUser1;
    private javax.swing.JLabel LbUser2;
    private javax.swing.JLabel UserNamee;
    private javax.swing.JLabel books;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBalance;
    private javax.swing.JLabel lbNOB1;
    private javax.swing.JLabel lbNOB2;
    private TaoNen.Nen nen1 ;}
