/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NutNhanMAC;


import javax.swing.JFrame;
import TaoNen.Nen;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ANH TUAN
 */
public class GopNutMAC extends javax.swing.JPanel {

    /**
     * Creates new form GopNutMAC
     */
    public GopNutMAC() {
        initComponents();
        setOpaque(false);
    }

     public void initEvent(JFrame fram, Nen panel) {
        cmdClose.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                System.exit(0);
            }
        });
        cmdMi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                fram.setState(JFrame.ICONIFIED);
            }
        });
        cmdRe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (fram.getExtendedState() == JFrame.MAXIMIZED_BOTH) {
                    panel.setRound(20);
                    fram.setExtendedState(JFrame.NORMAL);
                } else {
                    panel.setRound(0);
                    fram.setExtendedState(JFrame.MAXIMIZED_BOTH);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        cmdRe = new NutNhanMAC.DangNut();
        cmdMi = new NutNhanMAC.DangNut();
        cmdClose = new NutNhanMAC.DangNut();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        cmdRe.setForeground(new java.awt.Color(51, 255, 51));
        cmdRe.setText("dangNut1");
        cmdRe.setMaximumSize(new java.awt.Dimension(20, 20));
        cmdRe.setMinimumSize(new java.awt.Dimension(20, 20));
        cmdRe.setPreferredSize(new java.awt.Dimension(20, 20));
        add(cmdRe);

        cmdMi.setForeground(new java.awt.Color(255, 255, 0));
        cmdMi.setText("dangNut2");
        cmdMi.setMaximumSize(new java.awt.Dimension(20, 20));
        cmdMi.setMinimumSize(new java.awt.Dimension(20, 20));
        cmdMi.setPreferredSize(new java.awt.Dimension(20, 20));
        add(cmdMi);

        cmdClose.setForeground(new java.awt.Color(255, 51, 51));
        cmdClose.setText("dangNut3");
        cmdClose.setMaximumSize(new java.awt.Dimension(20, 20));
        cmdClose.setMinimumSize(new java.awt.Dimension(20, 20));
        cmdClose.setPreferredSize(new java.awt.Dimension(20, 20));
        add(cmdClose);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private NutNhanMAC.DangNut cmdClose;
    private NutNhanMAC.DangNut cmdMi;
    private NutNhanMAC.DangNut cmdRe;
    // End of variables declaration                   
}
